[/]
close=['<Control>q', '<Alt>F4']
maximize=@as []
maximize-horizontally=['<Super>n']
maximize-vertically=['<Super>b']
minimize=@as []
move-to-workspace-1=['<Alt><Super>1']
move-to-workspace-2=['<Alt><Super>2']
move-to-workspace-3=['<Alt><Super>3']
move-to-workspace-4=['<Alt><Super>4']
move-to-workspace-left=['<Shift><Super>j']
move-to-workspace-right=['<Shift><Super>k']
switch-to-workspace-1=@as []
switch-to-workspace-left=['<Control><Super>j']
switch-to-workspace-right=['<Control><Super>k']
toggle-maximized=['<Super>m']
